version: '3.9'

services:
  meetup-postgres:
    image: postgres:13
    container_name: meetup-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=store
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres