server.port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}/restaurant?currentSchema=restaurant
    username: postgres
    password: postgres

  jpa:
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true

kafka.topics.restaurantEventsTopic: restaurant-events-topic